FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV GITHUB_DEEP_SEARCH_HOST=0.0.0.0
ENV GITHUB_DEEP_SEARCH_PORT=8001
ENV GITHUB_DEEP_SEARCH_RELOAD=0

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8001

CMD ["python", "run_web.py"]
